services:
  postgres:
    image: postgres
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "5432:5432"
    networks:
      my_custom_network:
        ipv4_address: 172.20.0.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - postgres_password
    deploy:
      resources:
        limits:
          cpus: '0.5'

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:

secrets:
  postgres_password:
    file: ./postgres_password.txt
