CREATE TABLE IF NOT EXISTS session (
    id SERIAL PRIMARY KEY,
    memberID INTEGER NOT NULL,
    sessionId VARCHAR(255) NOT NULL,
    loginTime TIMESTAMP NOT NULL,
    CONSTRAINT fk_member FOREIGN KEY(memberID) REFERENCES member(memberID)
);